# Generated by Django 4.0.1 on 2022-02-01 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_alter_product_discount_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_meta',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.product', unique=True),
        ),
    ]
