# Generated by Django 4.0.1 on 2022-02-01 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_alter_product_meta_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_meta',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myshop.product'),
        ),
        migrations.CreateModel(
            name='Product_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
                ('is_publish', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creat date')),
                ('published_at', models.DateTimeField(null=True, verbose_name='publish date')),
                ('content', models.TextField()),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myshop.product_review')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.product')),
            ],
        ),
    ]
