# Generated by Django 4.0.1 on 2022-02-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_category_alter_product_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myshop.product'),
        ),
        migrations.AlterField(
            model_name='product_review',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_review',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
