# Generated by Django 4.0.1 on 2022-02-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0011_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create date'),
        ),
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Update date')),
                ('content', models.TextField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.product')),
            ],
        ),
    ]
