# Generated by Django 3.1.13 on 2022-01-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220110_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permissions',
        ),
    ]
