# Generated by Django 4.0.1 on 2022-02-10 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 2, 10, 5, 58, 46, 324459, tzinfo=utc)),
        ),
    ]
